### ISSUE TITLE
Possible error in estate.property.offer:action_accept

### ISSUE THREAD

**Issue by madprog** [odoo/technical-training-solutions#46]
https://github.com/odoo/technical-training-solutions/blob/a3b24b625b497bc3cecccf7ecf4a31779aa48e0d/estate/models/estate_property_offer.py#L85-L91

If you are accepting several offers at once, won't this code set the `buyer_id` and `selling_price` of the first offer of the record_set to all the corresponding properties, even those whose accepted offer is from a different `buyer_id` and/or at a different `selling_price`?

**Comment by yousseftarhri** [comment]
Since `property_id` is a **Many2one** field pointing to the **estate.property** model, this means each offer will reference exactly one property, and there should only be one `property_id` associated with each offer in the mapped recordset. Therefore, when you call self.mapped("property_id"), you're essentially working with a collection of unique property records, each corresponding to a single property associated with the offers.

**Comment by yousseftarhri** [comment]
> https://github.com/odoo/technical-training-solutions/blob/a3b24b625b497bc3cecccf7ecf4a31779aa48e0d/estate/models/estate_property_offer.py#L85-L91
> 
> If you are accepting several offers at once, won't this code set the `buyer_id` and `selling_price` of the first offer of the record_set to all the corresponding properties, even those whose accepted offer is from a different `buyer_id` and/or at a different `selling_price`?

Since `property_id` is a **Many2one** field pointing to the **estate.property** model, this means each offer will reference exactly one property, and there should only be one `property_id` associated with each offer in the mapped recordset. Therefore, when you call **self.mapped("property_id")**, you're essentially working with a collection of unique property records, each corresponding to a single property associated with the offers.

**Comment by madprog** [comment]
Hello @yousseftarhri and thank you for your answer. I totally forgot about this since 4 years ago!
The case that I was talking about is not possible anyway, because given this situation:
```python
>>> env['estate.property.offer'].search_read([], ['price', 'property_id'])
[
    {'id': 1, 'price': 190000.0, 'property_id': (2, 'Property2')},
    {'id': 2, 'price': 195000.0, 'property_id': (2, 'Property2')},
    {'id': 3, 'price': 90000.0, 'property_id': (1, 'Property1')},
    {'id': 4, 'price': 95000.0, 'property_id': (1, 'Property1')},
]
```
The following code results in an exception anyway, because the `action_validate` method doesn't support when `self` is not a singleton:
```python
>>> env['estate.property.offer'].browse([2, 4]).action_accept()
Traceback (most recent call last):
  File "/home/madprog/workspace/odoo/src/14.0/odoo/odoo/models.py", line 5047, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/madprog/workspace/odoo/src/technical-training-sandbox/estate/models/estate_property_offer.py", line 88, in action_accept
    "selling_price": self.price,
  File "/home/madprog/workspace/odoo/src/14.0/odoo/odoo/fields.py", line 987, in __get__
    record.ensure_one()
  File "/home/madprog/workspace/odoo/src/14.0/odoo/odoo/models.py", line 5050, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: estate.property.offer(2, 4)
```
